services:
  react-vite-app2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_API_URL: "https://dashboard.makkahhc.sa/api"  
    ports:
      - '3000:80' 
    container_name: react-vite-app2
    restart: unless-stopped