# Generated by Django 5.2.4 on 2025-10-04 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in m', null=True)),
                ('physical_activity', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise) — 1.2'), ('light', 'Lightly active (30 min moderate, 1-3 days/week) — 1.375'), ('moderate', 'Moderately active (45 min, 3-5 days/week) — 1.55'), ('very_active', 'Very active (1 hr, 6-7 days/week) — 1.725'), ('extra', 'Extra active (hard training + weight lifting) — 1.9')], max_length=20)),
                ('ward_type', models.CharField(blank=True, choices=[('outpatient', 'Out-patient'), ('icu', 'ICU'), ('medical', 'Medical Ward'), ('cardiac', 'Cardiac Ward'), ('others', 'Others')], max_length=50, null=True)),
                ('stress_factor', models.CharField(blank=True, choices=[('minor_surgery', 'Minor Surgery — 1.1'), ('major_surgery', 'Major Surgery — 1.2'), ('skeletal_trauma', 'Skeletal Trauma — 1.2'), ('blunt_trauma', 'Blunt Trauma — 1.35'), ('closed_head_injury', 'Closed Head Injury — 1.4'), ('mild_infection', 'Mild Infection — 1.2'), ('moderate_infection', 'Moderate Infection — 1.4'), ('severe_infection', 'Severe Infection — 1.8'), ('starvation', 'Starvation — 0.85'), ('burns_lt_20', 'Burns <20% TBSA — 1.5'), ('burns_20_40', 'Burns 20%-40% TBSA — 1.8'), ('burns_gt_40', 'Burns >40% TBSA — 2.0')], max_length=30, null=True)),
                ('feeding_type', models.CharField(blank=True, choices=[('oral', 'Oral'), ('enteral_parenteral', 'Enteral & Parenteral'), ('tpn', 'TPN')], max_length=50, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('initial', 'initial'), ('follow_up', 'follow_up')], max_length=20)),
                ('status', models.CharField(choices=[('next', 'next'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='next', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in m', null=True)),
                ('physical_activity', models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise) — 1.2'), ('light', 'Lightly active (30 min moderate, 1-3 days/week) — 1.375'), ('moderate', 'Moderately active (45 min, 3-5 days/week) — 1.55'), ('very_active', 'Very active (1 hr, 6-7 days/week) — 1.725'), ('extra', 'Extra active (hard training + weight lifting) — 1.9')], max_length=20, null=True)),
                ('ward_type', models.CharField(blank=True, choices=[('outpatient', 'Out-patient'), ('icu', 'ICU'), ('medical', 'Medical Ward'), ('cardiac', 'Cardiac Ward'), ('others', 'Others')], max_length=50, null=True)),
                ('stress_factor', models.CharField(blank=True, choices=[('minor_surgery', 'Minor Surgery — 1.1'), ('major_surgery', 'Major Surgery — 1.2'), ('skeletal_trauma', 'Skeletal Trauma — 1.2'), ('blunt_trauma', 'Blunt Trauma — 1.35'), ('closed_head_injury', 'Closed Head Injury — 1.4'), ('mild_infection', 'Mild Infection — 1.2'), ('moderate_infection', 'Moderate Infection — 1.4'), ('severe_infection', 'Severe Infection — 1.8'), ('starvation', 'Starvation — 0.85'), ('burns_lt_20', 'Burns <20% TBSA — 1.5'), ('burns_20_40', 'Burns 20%-40% TBSA — 1.8'), ('burns_gt_40', 'Burns >40% TBSA — 2.0')], max_length=30, null=True)),
                ('feeding_type', models.CharField(blank=True, choices=[('oral', 'Oral'), ('enteral_parenteral', 'Enteral & Parenteral'), ('tpn', 'TPN')], max_length=50, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=50, null=True)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='clients.client')),
                ('follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='clients.followup')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clients.client')),
                ('follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clients.followup')),
            ],
        ),
    ]
