# Generated by Django 5.2.4 on 2025-09-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='user',
        ),
    ]
