# Generated by Django 5.2.4 on 2025-10-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='feeding_type',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('enteral_parenteral', 'Enteral & Parenteral'), ('tpn', 'TPN')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in m', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ward_type',
            field=models.CharField(blank=True, choices=[('outpatient', 'Out-patient'), ('icu', 'ICU'), ('medical', 'Medical Ward'), ('cardiac', 'Cardiac Ward'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='reference_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='clients.client')),
            ],
        ),
    ]
