# Generated by Django 5.2.4 on 2025-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_is_finished_alter_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.AddField(
            model_name='followup',
            name='feeding_type',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('enteral_parenteral', 'Enteral & Parenteral'), ('tpn', 'TPN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in m', null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise) — 1.2'), ('light', 'Lightly active (30 min moderate, 1-3 days/week) — 1.375'), ('moderate', 'Moderately active (45 min, 3-5 days/week) — 1.55'), ('very_active', 'Very active (1 hr, 6-7 days/week) — 1.725'), ('extra', 'Extra active (hard training + weight lifting) — 1.9')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='stress_factor',
            field=models.CharField(blank=True, choices=[('minor_surgery', 'Minor Surgery — 1.1'), ('major_surgery', 'Major Surgery — 1.2'), ('skeletal_trauma', 'Skeletal Trauma — 1.2'), ('blunt_trauma', 'Blunt Trauma — 1.35'), ('closed_head_injury', 'Closed Head Injury — 1.4'), ('mild_infection', 'Mild Infection — 1.2'), ('moderate_infection', 'Moderate Infection — 1.4'), ('severe_infection', 'Severe Infection — 1.8'), ('starvation', 'Starvation — 0.85'), ('burns_lt_20', 'Burns <20% TBSA — 1.5'), ('burns_20_40', 'Burns 20%-40% TBSA — 1.8'), ('burns_gt_40', 'Burns >40% TBSA — 2.0')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='ward_type',
            field=models.CharField(blank=True, choices=[('outpatient', 'Out-patient'), ('icu', 'ICU'), ('medical', 'Medical Ward'), ('cardiac', 'Cardiac Ward'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
