# Generated by Django 5.2.4 on 2025-10-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_age_followup_feeding_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='clients.followup'),
        ),
        migrations.AddField(
            model_name='medication',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clients.followup'),
        ),
    ]
