import { MealPlanTemplateRow } from './types';

export const initialRows: MealPlanTemplateRow[] = [
  {
    id: 1,
    templateName: 'Keto Diet',
    calories: '1200 kcal',
    carbohydrates: '100 g',
    protein: '100 g',
    fat: '100 g',
  },
  {
    id: 2,
    templateName: 'Mediterranean Diet',
    calories: '1500 kcal',
    carbohydrates: '150 g',
    protein: '120 g',
    fat: '80 g',
  },
  {
    id: 3,
    templateName: 'Vegan Diet',
    calories: '1800 kcal',
    carbohydrates: '200 g',
    protein: '100 g',
    fat: '70 g',
  },
  {
    id: 4,
    templateName: 'Paleo Diet',
    calories: '1400 kcal',
    carbohydrates: '80 g',
    protein: '140 g',
    fat: '90 g',
  },
  {
    id: 5,
    templateName: 'Low Carb',
    calories: '1300 kcal',
    carbohydrates: '50 g',
    protein: '150 g',
    fat: '100 g',
  },
  {
    id: 6,
    templateName: 'High Protein',
    calories: '1600 kcal',
    carbohydrates: '120 g',
    protein: '180 g',
    fat: '60 g',
  },
  {
    id: 7,
    templateName: 'Balanced Diet',
    calories: '1500 kcal',
    carbohydrates: '150 g',
    protein: '120 g',
    fat: '80 g',
  },
  {
    id: 8,
    templateName: 'Weight Loss',
    calories: '1000 kcal',
    carbohydrates: '80 g',
    protein: '100 g',
    fat: '50 g',
  },
  {
    id: 9,
    templateName: 'Muscle Gain',
    calories: '2000 kcal',
    carbohydrates: '200 g',
    protein: '200 g',
    fat: '100 g',
  },
];