# Generated by Django 5.2.4 on 2025-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_platforms_connectedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='platform_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='stream_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platforms',
            name='auth_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platforms',
            name='stream_key_required',
            field=models.BooleanField(default=False),
        ),
    ]
