# Generated by Django 5.2.4 on 2025-08-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_connectedaccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
